# Generated by Django 5.1.7 on 2025-03-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySqlDjango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
